### ISSUE TITLE
package-autoremove tries to delete packages installed by `package-vc.el`.

### ISSUE THREAD

**Issue by amano-kenji** [slotThe/vc-use-package#17]
Packages installed by `package-vc.el` go to `package-vc-selected-packages`.

`package-autoremove` tries to delete anything that's not in `package-selected-packages` or is not dependencies of `package-selected-packages`.

Is there a solution?

**Comment by slotThe** [comment]
This seems to be fixed in recent enough versions of Emacs; for me (currently running `21e272fe4f336827611c4005a56829a0ab02f3f8`) `package-vc--unpack-1` (called by `package-vc-install`) contains the following lines:

``` emacs-lisp
    ;; Mark package as selected
    (let ((name (package-desc-name pkg-desc)))
      (unless (memq name package-selected-packages)
        (package--save-selected-packages
         (cons name package-selected-packages))))
```

EDIT: You can always add an `:after` advice to `package-vc-install` if you're still on a version of Emacs not supporting this, of course

**Comment by amano-kenji** [comment]
`package-vc-install` doesn't support `:after` in emacs 29.1.

**Comment by slotThe** [comment]
This is not something that `package-vc-install` has to support, I'm talking about `advice-add`ing an `:after` advice that does essentially what `package-vc--unpack-1` does nowadays
